name: test-win32-mingw64
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  imager:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - name: set up perl
        run: |
            choco install strawberryperl
            echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"
      - name: configure
        run: |
           perl Makefile.PL
      - name: build
        run: |
            gmake -j2
      - name: test
        run: |
            set HARNESS_OPTIONS=j2
            gmake test
